### ISSUE TITLE
Clicking on Notification doesn't open the app.

### ISSUE THREAD

**Issue by MorgeMoensch** [republik/app#271]
## Bug Report

When clicking on a Notification from a Reply, the app doesn't open.

**Steps to Reproduce**

Get a reply to a comment of yours. Then, click on the notification you get.

**Actual Results**

Notification disappears, app does not open.

**Expected Results**

App opens and scrolls to the comment of the notification I tapped on.

**Environment**

- OS: Android 12
- App Version: 2.2.0

**Possible Solutions**

**Comment by ovbm** [comment]
Thanks for reporting, we area having some issues with our notification solution and Android 11+, will be releasing an update shortly: See: https://github.com/republik/app/issues/273
